# -*- coding: utf-8 -*-
"""Drunk detection (thermal picture)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZINGCOIag4mT9Wz6t5jVMs6tgPjMfmN1

# AI-BASED SYSTEM FOR IDENTIFYING ALCOHOL INTOXICATION
# Date: 7/10/2025
# Group: 14

## I. Install library
"""

import numpy as np
import pandas as pd
import os
import os.path
import cv2
import matplotlib.pyplot as plt
import gdown

"""## II. Load Dataset"""

# URL chia sẻ file annotations.csv
url = "https://drive.google.com/file/d/13N40_NbWL6qBgZGqK5tRybjKPKp9YtE0/view?usp=drive_link"

# Tải file với tùy chọn --fuzzy
gdown.download(url, output="annotations.csv", quiet=False, fuzzy=True)

# đọc file với các tùy chọn
df = pd.read_csv("annotations.csv", sep=",", encoding="utf-8", on_bad_lines="skip")
print(df.head())

"""## III. Preprocessing

"""

# ====== 1. Import Libraries ======
import os
import cv2
import pandas as pd
from google.colab import drive

# ====== 2. Mount Google Drive ======
drive.mount('/content/drive')

# ====== 3. Set Paths and Target Size ======
target_width, target_height = 640, 640
csv_path = "/content/drive/MyDrive/retrain_thermal_picture/annotation/annotations.csv"
image_folder = "/content/drive/MyDrive/retrain_thermal_picture/dataset/"
debug_folder = os.path.join(image_folder, "debug")  # Folder for debug images

# ====== 1. Import Libraries ======
import os
import cv2
import pandas as pd
from google.colab import drive

# ====== 2. Mount Google Drive ======
drive.mount('/content/drive')

# ====== 3. Set Paths and Target Size ======
target_width, target_height = 640, 640
csv_path = "/content/drive/MyDrive/retrain_thermal_picture/annotation/annotations.csv" # Use the downloaded file path

image_folder = "/content/drive/MyDrive/retrain_thermal_picture/dataset" # Assuming images are still in Drive
debug_folder = os.path.join(image_folder, "debug")  # Folder for debug images

# Create debug folder if it doesn't exist
os.makedirs(debug_folder, exist_ok=True)

# ====== 4. Check if CSV Exists ======
if not os.path.exists(csv_path):
    raise FileNotFoundError(f"Không tìm thấy file CSV tại: {csv_path}")

# ====== 5. Read CSV Data ======
df = pd.read_csv(csv_path, sep=",", encoding="utf-8", on_bad_lines="skip")

# Check the available columns in the dataframe
print("\nAvailable columns in the dataframe:")
print(df.columns)

# ====== 6. Display Data Before Update ======
# Use the correct column names based on the available columns
print("\n=== Trước khi cập nhật ===")
# Assuming the bounding box columns are 'x_center', 'y_center', 'width', 'height' from the previous output
# We need to calculate xmin, ymin, xmax, ymax from these columns
df['xmin'] = df['x_center'] - df['width'] / 2
df['ymin'] = df['y_center'] - df['height'] / 2
df['xmax'] = df['x_center'] + df['width'] / 2
df['ymax'] = df['y_center'] + df['height'] / 2

print(df[['filename', 'xmin', 'ymin', 'xmax', 'ymax']].head())


# ====== 7. Resize Images and Update Bounding Boxes ======
# Group by filename to handle multiple bounding boxes per image
grouped = df.groupby('filename')

for filename, group in grouped:
    image_path = os.path.join(image_folder, filename)

    # Check if image exists
    if not os.path.exists(image_path):
        print(f"[!] Không tìm thấy ảnh: {filename}")
        continue

    # Read image
    img = cv2.imread(image_path)
    if img is None:
        print(f"[!] Không thể đọc ảnh: {filename}")
        continue

    # Get original dimensions
    h, w = img.shape[:2]
    scale_x = target_width / w
    scale_y = target_height / h

    # Log scaling factors
    print(f"\n[Debug] Xử lý ảnh: {filename}")
    print(f"  Kích thước gốc: {w}x{h}")
    print(f"  Kích thước đích: {target_width}x{target_height}")
    print(f"  Tỷ lệ scale: scale_x={scale_x:.4f}, scale_y={scale_y:.4f}")

    # Update bounding boxes for all rows associated with this image
    for idx in group.index:
        print(f"  [Debug] Index: {idx}, Bounding box gốc: "
              f"xmin={df.at[idx, 'xmin']:.2f}, ymin={df.at[idx, 'ymin']:.2f}, "
              f"xmax={df.at[idx, 'xmax']:.2f}, ymax={df.at[idx, 'ymax']:.2f}")

        # Update image dimensions
        df.at[idx, 'width'] = target_width
        df.at[idx, 'height'] = target_height

        # Update bounding box coordinates
        if pd.notna(df.at[idx, 'xmin']) and pd.notna(df.at[idx, 'xmax']) and \
           pd.notna(df.at[idx, 'ymin']) and pd.notna(df.at[idx, 'ymax']):
            df.at[idx, 'xmin'] = float(df.at[idx, 'xmin']) * scale_x
            df.at[idx, 'xmax'] = float(df.at[idx, 'xmax']) * scale_x
            df.at[idx, 'ymin'] = float(df.at[idx, 'ymin']) * scale_y
            df.at[idx, 'ymax'] = float(df.at[idx, 'ymax']) * scale_y

            # Clip bounding box coordinates to image boundaries
            df.at[idx, 'xmin'] = min(max(0, df.at[idx, 'xmin']), target_width)
            df.at[idx, 'xmax'] = min(max(0, df.at[idx, 'xmax']), target_width)
            df.at[idx, 'ymin'] = min(max(0, df.at[idx, 'ymin']), target_height)
            df.at[idx, 'ymax'] = min(max(0, df.at[idx, 'ymax']), target_height)


            print(f"  [Debug] Bounding box mới: "
                  f"xmin={df.at[idx, 'xmin']:.2f}, ymin={df.at[idx, 'ymin']:.2f}, "
                  f"xmax={df.at[idx, 'xmax']:.2f}, ymax={df.at[idx, 'ymax']:.2f}")
        else:
            print(f"[!] Bounding box không hợp lệ tại index {idx} cho ảnh {filename}")


# ====== 8. Display Data After Update ======
print("\n=== Sau khi cập nhật ===")
print(df[['filename', 'xmin', 'ymin', 'xmax', 'ymax']].head())

# ====== 9. Save Updated CSV ======
# Save the updated CSV to the same location where it was read from
df.to_csv(csv_path, index=False, encoding="utf-8")
print("\nĐã cập nhật annotations.csv và resize ảnh thành công.")

import matplotlib.pyplot as plt
import cv2
import os
import pandas as pd

def plot_sample_images_with_bboxes(df, image_folder, num_images=5):
    # Lấy danh sách các ảnh duy nhất có trong annotations
    unique_filenames = df['filename'].unique()[:num_images]

    for filename in unique_filenames:
        image_path = os.path.join(image_folder, filename)
        if not os.path.exists(image_path):
            print(f"[!] Không tìm thấy ảnh: {filename}")
            continue

        # Đọc ảnh và chuyển BGR → RGB để hiển thị đúng màu
        img = cv2.imread(image_path)
        if img is None:
            print(f"[!] Không thể đọc ảnh: {filename}")
            continue

        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        # Lấy các dòng annotation cho ảnh này
        annots = df[df['filename'] == filename]

        # Vẽ bounding boxes
        for _, row in annots.iterrows():
            xmin, ymin, xmax, ymax = map(int, [row['xmin'], row['ymin'], row['xmax'], row['ymax']])
            label = row['label'] # Changed from 'class' to 'label'
            cv2.rectangle(img_rgb, (xmin, ymin), (xmax, ymax), (255, 0, 0), 2)
            cv2.putText(img_rgb, label, (xmin, max(ymin - 10, 10)),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

        # Hiển thị ảnh
        plt.figure(figsize=(6, 6))
        plt.imshow(img_rgb)
        plt.title(f"File: {filename}")
        plt.axis('off')
        plt.show()

# Gọi hàm hiển thị ảnh
plot_sample_images_with_bboxes(df, image_folder, num_images=5)

# Nếu cột 'class' là NaN hoặc rỗng, gán giá trị là 'normal'
df['class_modified'] = df['label'].fillna('normal')

# Đếm số lượng ảnh duy nhất theo từng class
image_per_class = df.groupby('class_modified')['filename'].nunique().sort_values(ascending=False)

# Đếm tổng số ảnh duy nhất
total_images = df['filename'].nunique()

# Hiển thị kết quả
print("Số lượng ảnh duy nhất theo từng class:")
print(image_per_class)
print(f"\nTổng số ảnh: {total_images}")

# Use the CSV reading and grouping logic to check for invalid annotations (e.g., missing bounding boxes or non-existent images).
import pandas as pd
import os
csv_path = "/content/drive/MyDrive/retrain_thermal_picture/annotation/annotations.csv"
image_folder = "/content/drive/MyDrive/retrain_thermal_picture/dataset"
df = pd.read_csv(csv_path, encoding="utf-8", on_bad_lines="skip")
grouped = df.groupby('filename')
for filename, group in grouped:
    if not os.path.exists(os.path.join(image_folder, filename)):
        print(f"Missing image: {filename}")
        df = df[df['filename'] != filename]
df.to_csv(csv_path, index=False, encoding="utf-8")

# ===== KHỐI CODE TĂNG CƯỜNG ẢNH "SOBER" =====
import random
import numpy as np
import cv2
import pandas as pd
import os

print("\n--- BẮT ĐẦU BƯỚC TĂNG CƯỜNG ẢNH (AUGMENTATION) ---")

# --- 1. ĐỊNH NGHĨA CÁC HÀM HỖ TRỢ ---

def transform_bbox_flip(bbox, img_width):
    """Biến đổi bounding box cho việc lật ngang."""
    xmin, ymin, xmax, ymax = bbox
    new_xmin = img_width - xmax
    new_xmax = img_width - xmin
    return new_xmin, ymin, new_xmax, ymax

def augment_image_sober(img):
    """
    Tạo một biến thể ảnh (lật hoặc thay đổi độ sáng) và trả về
    ảnh đã biến đổi cùng thông tin (transform_type).
    """
    h, w = img.shape[:2]

    # Chọn ngẫu nhiên một phép biến đổi
    choice = random.choice(['flip', 'brightness'])

    if choice == 'flip':
        # Lật ngang
        augmented_img = cv2.flip(img, 1)
        transform_info = ('flip', None)
        print("  [Debug] Augment: Lật ngang")
    else:
        # Thay đổi độ sáng
        brightness = random.uniform(0.7, 1.3)
        # Đảm bảo ảnh là kiểu float để nhân độ sáng, sau đó chuyển lại uint8
        img_float = img.astype(np.float32)
        augmented_img = np.clip(img_float * brightness, 0, 255).astype(np.uint8)
        transform_info = ('brightness', None)
        print(f"  [Debug] Augment: Độ sáng (factor={brightness:.2f})")

    return augmented_img, transform_info

# --- 2. THIẾT LẬP BIẾN VÀ ĐỌC DỮ LIỆU ---

# Đọc lại file CSV đã được làm sạch và resize từ bước trước
try:
    df = pd.read_csv(csv_path, sep=",", encoding="utf-8", on_bad_lines="skip")
except NameError:
    print("LỖI: Các biến csv_path hoặc image_folder chưa được định nghĩa.")
    # Xử lý lỗi nếu cần

# --- 3. TÍNH TOÁN SỐ LƯỢNG ---

# Lấy danh sách file duy nhất cho mỗi lớp
file_class_map = df.groupby('filename')['label'].apply(set)
sober_files = [f for f, labels in file_class_map.items() if 'Sober' in labels and 'Drunk' not in labels]
drunk_files_count = len([f for f, labels in file_class_map.items() if 'Drunk' in labels])
sober_files_count = len(sober_files)

num_to_augment = drunk_files_count - sober_files_count

print(f"Số ảnh 'Drunk' (mục tiêu): {drunk_files_count}")
print(f"Số ảnh 'Sober' (hiện tại): {sober_files_count}")
print(f"Số ảnh 'Sober' cần tăng cường: {num_to_augment}")

# --- 4. THỰC HIỆN TĂNG CƯỜNG ---

augmented_rows = []
if num_to_augment > 0 and sober_files:
    for i in range(num_to_augment):
        # Chọn ngẫu nhiên một file 'Sober' gốc để tăng cường
        filename_to_aug = random.choice(sober_files)
        original_path = os.path.join(image_folder, filename_to_aug)

        img = cv2.imread(original_path)
        if img is None:
            print(f"[!] Bỏ qua: Không thể đọc ảnh {filename_to_aug}")
            continue

        # Lấy thông tin annotation gốc
        anns = df[df['filename'] == filename_to_aug].copy()

        # Tạo ảnh tăng cường
        aug_img, (transform_type, transform_data) = augment_image_sober(img)

        # Tạo tên file mới và lưu ảnh
        new_name = f"aug_sober_{i}_{filename_to_aug}"
        new_path = os.path.join(image_folder, new_name)
        cv2.imwrite(new_path, aug_img) # Lưu ảnh tăng cường vật lý

        print(f"  -> Đã tạo: {new_name}")

        # Tạo các hàng annotation mới cho ảnh tăng cường
        for _, row in anns.iterrows():
            new_row = row.copy()
            new_row['filename'] = new_name
            # Kích thước ảnh không đổi vì chúng ta augment sau khi resize
            new_row['width'] = target_width
            new_row['height'] = target_height

            # Biến đổi Bounding Box nếu cần
            if pd.notna(row['xmin']): # Chỉ biến đổi nếu có bbox
                bbox = (row['xmin'], row['ymin'], row['xmax'], row['ymax'])

                if transform_type == 'flip':
                    new_bbox = transform_bbox_flip(bbox, target_width)
                else: # 'brightness' không thay đổi bbox
                    new_bbox = bbox

                new_row['xmin'], new_row['ymin'], new_row['xmax'], new_row['ymax'] = new_bbox

            augmented_rows.append(new_row.to_dict())

else:
    print("Không cần tăng cường hoặc không có ảnh 'Sober' để tăng cường.")

# --- 5. LƯU KẾT QUẢ ---

if augmented_rows:
    # Tạo DataFrame từ các hàng mới
    df_augmented = pd.DataFrame(augmented_rows)

    # Nối DataFrame gốc với DataFrame tăng cường
    df_final = pd.concat([df, df_augmented], ignore_index=True)

    # Lưu lại file CSV (ghi đè file cũ với dữ liệu đã tăng cường)
    df_final.to_csv(csv_path, index=False, encoding="utf-8")

    print(f"\nĐÃ TĂNG CƯỜNG VÀ LƯU THÀNH CÔNG {len(augmented_rows)} ANNOTATIONS MỚI.")

    # Kiểm tra lại số lượng
    df_final['class_modified'] = df_final['label'].fillna('normal')
    image_per_class_final = df_final.groupby('class_modified')['filename'].nunique().sort_values(ascending=False)
    print("\nSố lượng ảnh duy nhất theo từng class (SAU KHI TĂNG CƯỜNG):")
    print(image_per_class_final)
else:
    print("\nKhông có thay đổi, giữ nguyên file annotations.csv.")

# ===== KẾT THÚC KHỐI CODE TĂNG CƯỜNG =====

"""## IV. Training YOLO"""

pip install ultralytics opencv-python

import ultralytics
ultralytics.__file__

from ultralytics import YOLO

base_dir = "/content/drive/MyDrive/retrain_thermal_picture/dataset"
for split in ['train', 'val', 'test']:
    os.makedirs(os.path.join(base_dir, 'images', split), exist_ok=True)
    os.makedirs(os.path.join(base_dir, 'labels', split), exist_ok=True)

# Chuyển Pascal VOC sang YOLO format: (class_id, x_center, y_center, width, height)
def convert_to_yolo(bbox, img_width, img_height):
    x_min, y_min, x_max, y_max = bbox
    x_center = (x_min + x_max) / 2 / img_width
    y_center = (y_min + y_max) / 2 / img_height
    width = (x_max - x_min) / img_width
    height = (y_max - y_min) / img_height
    return [x_center, y_center, width, height]

all_classes = ['Drunk', 'Sober']

# Sắp xếp để đảm bảo thứ tự nhất quán 
all_classes = sorted(all_classes)

# Ánh xạ từ tên class sang ID (YOLO format yêu cầu ID là số nguyên)
class_to_id = {cls_name: idx for idx, cls_name in enumerate(all_classes)}

print("Class to ID mapping:")
for k, v in class_to_id.items():
    print(f"{k}: {v}")

import os
import pandas as pd
import cv2
import numpy as np
from sklearn.model_selection import train_test_split
from pathlib import Path

# Paths
base_dir = "/content/drive/MyDrive/retrain_thermal_picture/"
image_folder = os.path.join(base_dir, "dataset")
csv_path = os.path.join(base_dir, "annotation", "annotations.csv")

# Create directories for YOLO dataset
for split in ['train', 'val', 'test']:
    os.makedirs(os.path.join(base_dir, 'images', split), exist_ok=True)
    os.makedirs(os.path.join(base_dir, 'labels', split), exist_ok=True)

# Read annotations.csv
df = pd.read_csv(csv_path, encoding="utf-8", on_bad_lines="skip")

# Extract class names and create class_to_id mapping
class_names = sorted(df['label'].unique())  # e.g., ['Drunk', 'Sober']
class_to_id = {name: idx for idx, name in enumerate(class_names)}
print(f"Classes: {class_names}, Mapping: {class_to_id}")

# Group annotations by filename
grouped = df.groupby('filename')

# Prepare data: images, bboxes, labels
images = []
bboxes = []
labels = []
image_class_map = {name: set() for name in class_names} # Track images by class
for filename, group in grouped:
    img_path = os.path.join(image_folder, filename)
    img = cv2.imread(img_path)
    if img is None:
        print(f"Skipping {filename}: Cannot read image")
        continue
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    images.append(img)
    boxes = group[['xmin', 'ymin', 'xmax', 'ymax']].values.tolist()
    bboxes.append(boxes)
    cls_labels = group['label'].values.tolist()
    labels.append(cls_labels)
    # Track classes in this image
    for cls in set(cls_labels):
        image_class_map[cls].add(filename)

# Save class summary files
for class_name, filenames in image_class_map.items():
    with open(os.path.join(base_dir, f'{class_name.lower()}_images.txt'), 'w') as f:
        f.write('\n'.join(sorted(filenames)))
print(f"Saved class summary files to {base_dir}")


# Split dataset (80% train, 10% val, 10% test)
data = list(zip(images, bboxes, labels))
train_data, test_data = train_test_split(data, test_size=0.1, random_state=42)
train_data, val_data = train_test_split(train_data, test_size=0.1, random_state=42)
splits = {'train': train_data, 'val': val_data, 'test': test_data}

# Function to convert bounding box to YOLO format
def convert_to_yolo(box, img_width, img_height):
    xmin, ymin, xmax, ymax = box
    center_x = (xmin + xmax) / 2 / img_width
    center_y = (ymin + ymax) / 2 / img_height
    width = (xmax - xmin) / img_width
    height = (ymax - ymin) / img_height
    return [center_x, center_y, width, height]

# Save images and labels
img_id = 0
for split_name, split_data in splits.items():
    for img_array, boxes, lbls in split_data:
        img_path = os.path.join(base_dir, 'images', split_name, f"fig_{img_id}.jpg")
        label_path = os.path.join(base_dir, 'labels', split_name, f"fig_{img_id}.txt")

        # Save image
        cv2.imwrite(img_path, cv2.cvtColor(img_array, cv2.COLOR_RGB2BGR))

        # Save YOLO labels
        h, w = img_array.shape[:2]
        with open(label_path, 'w') as f:
            for box, lbl in zip(boxes, lbls):
                yolo_box = convert_to_yolo(box, w, h)
                class_id = class_to_id[lbl]
                f.write(f"{class_id} {' '.join(map(str, yolo_box))}\n")

        img_id += 1

print(f"Dataset created: {len(train_data)} train, {len(val_data)} val, {len(test_data)} test images")

from collections import defaultdict

def count_classes_in_split(split_dir):
    label_dir = os.path.join(base_dir, "labels", split_dir)
    total_images = 0
    class_counts = defaultdict(int)

    for label_file in os.listdir(label_dir):
        if not label_file.endswith(".txt"):
            continue
        total_images += 1
        with open(os.path.join(label_dir, label_file), "r") as f:
            for line in f:
                class_id = int(line.strip().split()[0])
                class_counts[class_id] += 1

    return total_images, class_counts

# Hiển thị thống kê cho từng tập
for split in ['train', 'val', 'test']:
    num_images, class_counter = count_classes_in_split(split)
    print(f"\n📁 Tập {split.upper()}:")
    print(f"🖼️  Số ảnh: {num_images}")
    for class_id, count in sorted(class_counter.items()):
        print(f"  - Class {class_id} ({class_names[class_id]}): {count} instances")

with open(os.path.join(base_dir, "data.yaml"), "w") as f:
    f.write(f"path: {base_dir}\n")
    f.write("train: images/train\n")
    f.write("val: images/val\n")
    f.write("test: images/test\n")
    f.write(f"nc: {len(class_names)}\n")
    f.write("names: " + str(class_names) + "\n")

import yaml

# Đọc class names từ yaml
yaml_path = "/content/drive/MyDrive/retrain_thermal_picture/data.yaml"
with open(yaml_path, 'r') as f:
    data_yaml = yaml.safe_load(f)
class_names = data_yaml['names']

# Hàm vẽ bounding box (giữ nguyên)
def draw_boxes(image_path, label_path, class_names, box_color=(255, 0, 0)):
    image = cv2.imread(image_path)
    if image is None:
        print(f"[!] Không thể đọc ảnh: {image_path}")
        return None

    h, w = image.shape[:2]

    if os.path.exists(label_path):
        with open(label_path, 'r') as f:
            lines = f.readlines()
            for line in lines:
                items = line.strip().split()
                if len(items) < 5:
                    continue
                class_id = int(items[0])
                x_center = float(items[1]) * w
                y_center = float(items[2]) * h
                width = float(items[3]) * w
                height = float(items[4]) * h
                x1 = int(x_center - width / 2)
                y1 = int(y_center - height / 2)
                x2 = int(x_center + width / 2)
                y2 = int(y_center + height / 2)
                label = class_names[class_id] if class_id < len(class_names) else str(class_id)
                cv2.rectangle(image, (x1, y1), (x2, y2), box_color, 2)
                cv2.putText(image, label, (x1, y1 - 5), cv2.FONT_HERSHEY_SIMPLEX, 0.6, box_color, 2)
    else:
        print(f"[i] Không có bbox: {image_path}")

    return cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Chọn một tập để hiển thị (train/val/test)
split = "val"
img_dir = f"{base_dir}/images/{split}"
label_dir = f"{base_dir}/labels/{split}"

# Lấy một số ảnh để hiển thị
image_files = [f for f in os.listdir(img_dir) if f.endswith(".jpg") or f.endswith(".png")]
sample_files = image_files[:6]  # Hiển thị 6 ảnh đầu

# Hiển thị ảnh
plt.figure(figsize=(15, 10))
for i, filename in enumerate(sample_files):
    img_path = os.path.join(img_dir, filename)
    label_path = os.path.join(label_dir, filename.replace('.jpg', '.txt').replace('.png', '.txt'))

    image = draw_boxes(img_path, label_path, class_names)
    if image is not None:
        plt.subplot(2, 3, i+1)
        plt.imshow(image)
        plt.axis('off')
        plt.title(filename)
plt.tight_layout()
plt.show()

from ultralytics import YOLO

# Load model YOLOv8n (nhẹ), hoặc v8s/m/l/x tùy sức mạnh
model = YOLO("yolov8m.pt")

# Train
model.train(
    data="/content/drive/MyDrive/retrain_thermal_picture/data.yaml",  # đường dẫn tới file yaml
    epochs=100,
    imgsz=640,
    batch=16,
    name="drunk_detection_yolov8m",
    project="/content/drive/MyDrive/retrain_thermal_picture/runs",
    patience=10,
    device= 0,  # hoặc "cpu"
)

"""## V. Results

Check Validate
"""

from ultralytics import YOLO

# Load lại mô hình đã huấn luyện
model = YOLO("/content/drive/MyDrive/Drunkeness (after augmentation)/runs/drunk_detection_yolov8m/weights/best.pt")

# Đánh giá lại mô hình trên tập validation
metrics = model.val()

# Hiển thị confusion matrix
metrics.confusion_matrix.plot()

"""Check test"""

from ultralytics import YOLO

# Load mô hình đã huấn luyện
# model = YOLO("/content/drive/MyDrive/Drunkeness (after augmentation)/runs/drunk_detection_yolov8m/weights/best.pt")

# Đánh giá mô hình trên tập test
metrics = model.val(data="/content/drive/MyDrive/Dataset/Drunkeness (after augmentation)/data.yaml", split='test')

# Hiển thị confusion matrix
metrics.confusion_matrix.plot()

"""## VI. Testing"""

from IPython.display import Image, display
import matplotlib.pyplot as plt
import cv2

# Load best model
model = YOLO("/content/drive/MyDrive/retrain_thermal_picture/runs/drunk_detection_yolov8m2/weights/best.pt")

# Dự đoán trên ảnh hoặc thư mục ảnh
results = model.predict(
    source="/content/drive/MyDrive/retrain_thermal_picture/images/test/fig_1400.jpg",  # ← đường dẫn ảnh hoặc thư mục ảnh    fig_1261.jpg -> fig_1401.jpg
    save=True,
    conf=0.25
)


# Hiển thị ảnh với bounding box trực tiếp
for result in results:
    # Lấy ảnh kết quả dạng array (BGR)
    img = result.plot()  # return numpy array with bounding boxes drawn

    # Chuyển từ BGR -> RGB (vì OpenCV dùng BGR, matplotlib dùng RGB)
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # Hiển thị bằng matplotlib
    plt.figure(figsize=(10, 10))
    plt.imshow(img_rgb)
    plt.axis("off")
    plt.show()

from IPython.display import Image, display
import matplotlib.pyplot as plt
import cv2

# Load best model
model = YOLO("/content/drive/MyDrive/retrain_thermal_picture/runs/drunk_detection_yolov8m2/weights/best.pt")

# Dự đoán trên ảnh hoặc thư mục ảnh
results = model.predict(
    source="/content/drive/MyDrive/retrain_thermal_picture/images/test/fig_1261.jpg",  # ← đường dẫn ảnh hoặc thư mục ảnh    fig_1261.jpg -> fig_1401.jpg
    save=True,
    conf=0.25
)


# Hiển thị ảnh với bounding box trực tiếp
for result in results:
    # Lấy ảnh kết quả dạng array (BGR)
    img = result.plot()  # return numpy array with bounding boxes drawn

    # Chuyển từ BGR -> RGB (vì OpenCV dùng BGR, matplotlib dùng RGB)
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # Hiển thị bằng matplotlib
    plt.figure(figsize=(10, 10))
    plt.imshow(img_rgb)
    plt.axis("off")
    plt.show()
